#!/bin/bash

apt-get update
apt-get -y upgrade

apt-get -y install apache2 php php-mysql php-gd php-curl php-imagick php-imap php-pear php-zip php-soap ssmtp libapache2-mod-php php-intl php-fileinfo php-mbstring graphicsmagick-imagemagick-compat paxctl ghostscript

mkdir -p /var/lock/apache2 /var/run/apache2

paxctl -Cm /usr/sbin/apache2

a2enconf php7*
a2enmod php7* rewrite


